---
title: "Loan Predictions Dashboard"
runtime: shiny
output: 
  flexdashboard::flex_dashboard:
    orientation: rows
    vertical_layout: fill
    source_code: https://github.com/gfilla/bankloanprediction
    social: [ "twitter", "facebook", "linkedin" ]

    
---

```{r setup, include=FALSE}

library(objectStoreR) 
library(flexdashboard)
library(dplyr)
library(jsonlite)
library(shiny)
library(httr)
library(R4WML)
library(plotly)
library(ggplot2)


#########################
## Configure WML       ##
#########################

## WML Credentials ##
  token_url <- "https://ibm-watson-ml.mybluemix.net/v3/identity/token"
  username <- '4fae7652-8cf5-4fc5-a90b-6a80e8120cd0'
  password <- 'e183a9fc-a67b-4aea-b787-59527a2da805'
  
  ## Get WML token
  auth_token <- get_wml_auth_token(token_url, username, password)
  
  ## Get authentication headers
  wml_url <- "https://ibm-watson-ml.mybluemix.net"
  auth_headers <- get_wml_auth_headers(wml_url, username, password)
  
  ## Define scoring endpoint
  scoring_url <- "https://ibm-watson-ml.mybluemix.net/v3/wml_instances/8a2b9093-833c-469c-b648-192bedbbbd4a/published_models/a80515c8-1f8a-412f-8a1f-98126f64c15f/deployments/041a650f-a1c3-4f89-a6bc-43ddd57fe138/online "
  
##################################
##   Configure Object Storage   ##
##################################
  
## Reading Object Storage
creds <-list(auth_url = "https://identity.open.softlayer.com",project = "object_storage_92c67982_0c6e_49a7_8bfd_c51c91ebdd53",project_id = "7babac2c6d62406abd107c4512e6ede0",region = "dallas",user_id = "e3a895ede0924c0abda1cdb7304b994c",domain_id = "2c66d8b212cb45ac95ec36fda57b9d26",domain_name = "1026855",username = "member_495df5f127778f229b9ccb86b13b4aa8b817ac81",password = "Vwx8y0n[,5LbsNEv",container = "AnalyticsUniversityBankMarketingModeling",tenantId = "undefined",filename = "Test_Scored.csv")

#this data comes from our object storage container - used for distribution plots
testScores <- objectStore.get(creds)


```

Predictive Model Evaluation
=====================================

Row  {.sidebar data-width=350}
-----------------------------------------------------------------------

### Customer Attributes and Prediction

```{r}

#coefficient 1 - Age
sliderInput("AGE", "Enter age of customer:",
            min = 17, max = 98, value = 30, step = 1
)

#coefficient 2 - Job Category
job_list <- list('Administrative','Blue Collar', 'Entrepreneur', 'Housemaid', 'Management', 'Retired', 'Self-employed', 'Services','Student','Technician','Unemployed','Unknown')
selectInput("JOB", "Enter customer's job category:",
           job_list, selected = 'University Degree'
)

#coefficient 3 - Marital Status
marital_list <- list('Divorced','Married','Single','Unknown')
selectInput("MARITAL", "Enter customer's marital status:",
          marital_list, selected = 'single'
)

#coefficient 4 - Education Level 
education_list = list('Basic - 4 Years','Basic - 6 Years', 'Basic - 9 Years', 'High School', 'Illiterate', 'Professional Courses', 'University Degree','Unknown')
selectInput("EDU", "Select customer education level:",
           education_list, selected = 'University Degree'
)

#coefficient 5 - Housing Loan? 
radioButtons("HOUSING", "Does customer have housing loan?",
           list("No",  "Unknown", "Yes"),inline=T )

#coefficient 6 - Personal loan
radioButtons("LOAN", "Does customer have personal loan?",
           list("No",  "Unknown", "Yes"),inline=T )


#coefficient 7 - Contacts this campaign
sliderInput("CAMP", "Number of contacts this campaign:",
            min = 1, max = 56, value = 10, step = 1
)

 
actionButton("getPrediction", "Submit Record to Watson Machine Learning", color="green")
#cat(toString(score[1]))
 

 toPredict <- eventReactive(input$getPrediction, {
    
    ## Create dataframe to send to WML
    toPredictDF <- data.frame(AGE =  input$AGE,
                              JOB = match(input$JOB,job_list),
                              MARITAL = match(input$MARITAL, marital_list),
                              EDU = match(input$EDU,education_list),
                              HOUSING = match(input$HOUSING,  list("No",  "Unknown", "Yes")),
                              LOAN = match(input$LOAN,  list("No",  "Unknown", "Yes"))  ,
                              CAMP = input$CAMP
                              )
    
    ## Convert Dataframe to WML payload
    scoringSample <- to_wml_payload(toPredictDF)
    
    ## Send payload to WML
    results <- wml_score(scoring_url, auth_headers, payload = scoringSample)
    
    ## Convert API response to DataFrame
    resultsDF <- from_wml_payload(results)
    
    cbind(toPredictDF, resultsDF[1])
    
   ## Split probability column into 2
    resultsDF$probability_no <- stringr::str_split_fixed(resultsDF$probability, ",", 2)[, 1]
    resultsDF$probability_yes <- stringr::str_split_fixed(resultsDF$probability, ",", 2)[, 2]
    
    ## Clean up split
    resultsDF$probability_no <- gsub("c\\(", "", resultsDF$probability_no)
    resultsDF$probability_yes <- gsub("\\)", "", resultsDF$probability_yes)
    
    resultsList <- list(resultsDF, results, toPredictDF) #returning inputs as well to populate table
    resultsList
  
  })

```

Row {data-height=150}
-----------------------------------------------------------------------

### Predicted probability of Yes Loan

```{r}


renderValueBox({
    probs <- toPredict()[[1]]
    prob_no <- paste0(round(as.numeric(probs$probability_no), 4)*100)
    prob_yes <- paste0(round(as.numeric(probs$probability_yes), 4)*100)
    
    valueBox(value =  prob_yes,
             color = ifelse(prob_no > prob_yes, "grey", "success"),
             icon = icon('balance-scale')
    )

  }) 

```


### Predicted probability of No Loan

```{r}

renderValueBox({
    probs <- toPredict()[[1]]
    prob_no <- paste0(round(as.numeric(probs$probability_no), 4)*100)
    prob_yes <- paste0(round(as.numeric(probs$probability_yes), 4)*100)
    
    valueBox(value =  prob_no,
             color = ifelse(prob_no > prob_yes, "warning", "grey"),
             icon = icon('balance-scale')
    )

  }) 
```

Row {data-height=100}
-----------------------------------------------------------------------


```{r}


selectInput("selectedVar", "Select Feature from Model:",
               names(testScores)[1:7], selected = "age")
 
```



Row {data-height=700}
-----------------------------------------------------------------------

### Distribution of Input Features

```{r}

output$hist <- renderPlotly({
    v <- input$selectedVar

    p <- plot_ly(x = testScores[v][testScores$actual_class == 1,]
          , type = "histogram", name = "Positive") %>% 
                add_trace(x = testScores[v][testScores$actual_class == 0,]
          , type = "histogram",   name = "Negative") 

    p
})

plotlyOutput('hist')

```

### JSON Returned from WML API

```{r}

renderPrint({
    jsonlite::toJSON(toPredict()[2], pretty = T)
  })

  
```
